/*
 * radio.c
 * SCK-2400 Firmware -- SpaceCommsKit
 *
 * Purpose:
 *   RF layer implementation. Handles RF driver init, TX/RX operations,
 *   TX power control, and SKY13317 RF switch GPIO control.
 *
 *   PHY: 2-GFSK 250 kbps, 2440 MHz, 125 kHz deviation
 *   RF Switch: SKY13317-373LF on DIO28 (2.4G path) and DIO29 (PA enable)
 *
 * RX Architecture:
 *   Uses TI RFQueue helper (RFQueue.h / RFQueue.c -- copied from SDK example).
 *   RFQueue_defineQueue() allocates a two-entry circular buffer.
 *   CMD_PROP_RX runs via RF_runCmd() with a callback on RF_EventRxEntryDone.
 *   Callback sets sRxPacketReady flag and copies packet to sRxStageBuf.
 *   radio_rxReady() polls the flag. radio_receive() copies to caller buffer.
 *
 *   Hard-won lesson (SDK 8_32):
 *   rfc_data_entry.h does NOT exist in the driverlib folder for cc13x2_cc26x2.
 *   All data queue types come from RFQueue.h which includes rf_data_entry.h
 *   via DeviceFamily_constructPath. Copy RFQueue.h and RFQueue.c from:
 *   SDK/examples/rtos/CC1352P_2_LAUNCHXL/prop_rf/rfPacketRx/ into project.
 *
 * SCK-DEV: RF_CONFIG  -- PHY settings live in sck2400.syscfg.
 *          Aliases in radio.h map to SysConfig-generated symbols.
 * SCK-DEV: TX_POWER   -- See radio_setTxPower(). Build system passes
 *          TX_POWER=BENCH or TX_POWER=FIELD via Makefile define.
 * SCK-DEV: TIMING     -- See radio_transmit() for timing notes.
 *
 * Reference: SCK-2400_Firmware_Requirements.md Section 3.2, 4.2, 4.3
 */

/* -----------------------------------------------------------------------
 * Includes
 * --------------------------------------------------------------------- */
#include "radio.h"
#include "telemetry.h"
#include "main.h"

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <unistd.h>

/* TI Drivers */
#include <ti/drivers/GPIO.h>
#include <ti/drivers/rf/RF.h>

/* Driverlib */
#include DeviceFamily_constructPath(driverlib/rf_prop_mailbox.h)

/* RF command structures and TX power tables (generated by SysConfig) */
#include "ti_radio_config.h"

/* SysConfig generated driver config (GPIO pin indices) */
#include "ti_drivers_config.h"

/* RFQueue -- TI helper for data queue management.
 * Copied from SDK examples/rtos/CC1352P_2_LAUNCHXL/prop_rf/rfPacketRx/.
 * Provides: RFQueue_defineQueue(), RFQueue_getDataEntry(), RFQueue_nextEntry()
 * Also pulls in rfc_dataEntryGeneral_t and dataQueue_t via rf_data_entry.h. */
#include "RFQueue.h"

/* -----------------------------------------------------------------------
 * Static (module-private) state -- TX
 * --------------------------------------------------------------------- */
static RF_Object  sRfObject;
static RF_Handle  sRfHandle   = NULL;
static bool       sRadioReady = false;

/* Forward declaration -- radio_rxStart defined after radio_transmit */
static bool radio_rxStart(void);

/* TX buffer -- length byte prepended for bVarLen=1 mode */
static uint8_t sTxBuf[256];

/* -----------------------------------------------------------------------
 * Static (module-private) state -- RX
 *
 * RX buffer sized for two data entries.
 * NUM_APPENDED_BYTES = 2: 1 status byte + 1 RSSI byte appended by RF core.
 * Buffer must be 4-byte aligned (RF core DMA requirement).
 *
 * Hard-won lesson: RFQueue_defineQueue uses lenSz=0 (no length prefix byte).
 * Packet length comes from the entry length field, not a prepended byte.
 * --------------------------------------------------------------------- */
#define SCK_RX_NUM_ENTRIES      4    /* 4 entries prevents queue-full drops when beacons fill queue */
#define SCK_RX_NUM_APPENDED     2    /* status byte + RSSI byte */

static uint8_t sRxDataEntryBuffer[RF_QUEUE_DATA_ENTRY_BUFFER_SIZE(
                                       SCK_RX_NUM_ENTRIES,
                                       SCK_RX_BUF_SIZE,
                                       SCK_RX_NUM_APPENDED)]
                                       __attribute__((aligned(4)));

static dataQueue_t sRxQueue;

/* Staging buffer -- callback copies packet here, rfTask reads it out.
 * Decouples the RF callback (interrupt context) from the task. */
static uint8_t  sRxStageBuf[SCK_RX_BUF_SIZE];
static uint8_t  sRxStageLen  = 0;
static volatile bool sRxPacketReady = false;
static bool     sRxRunning   = false;

/* -----------------------------------------------------------------------
 * radio_rxCallback()  [module-private, called from RF driver interrupt]
 *
 * Purpose:
 *   RF driver callback, fired on RF_EventRxEntryDone when the RF core
 *   completes writing a received packet into the data queue.
 *   Copies packet to staging buffer and sets sRxPacketReady flag.
 *   rfTask polls radio_rxReady() and calls radio_receive() to read it out.
 *
 * Context: RF driver callback -- keep short, no blocking calls.
 * --------------------------------------------------------------------- */
static void radio_rxCallback(RF_Handle h, RF_CmdHandle ch, RF_EventMask e)
{
    if (e & RF_EventRxEntryDone)
    {
        rfc_dataEntryGeneral_t *entry = RFQueue_getDataEntry();

        uint8_t *pData  = (uint8_t *)(&entry->data);
        uint8_t  airLen = pData[0];

        if (airLen > 0 && airLen <= SCK_RX_BUF_SIZE)
        {
            /* Appended bytes follow the packet: status byte then RSSI byte.
             * status bit 7 = CRC OK (1) or bad (0). */
            uint8_t statusByte = pData[1 + airLen];
            int8_t  rssi       = (int8_t)pData[1 + airLen + 1];
            bool    goodCrc    = (statusByte & 0x80) != 0;

            telemetry_update_rx(rssi, 0, goodCrc);

            if (!sRxPacketReady)
            {
                memcpy(sRxStageBuf, pData + 1, airLen);
                sRxStageLen    = airLen;
                sRxPacketReady = true;
            }
            else if (airLen < sRxStageLen)
            {
                memcpy(sRxStageBuf, pData + 1, airLen);
                sRxStageLen = airLen;
            }
        }

        RFQueue_nextEntry();
    }
}

/* -----------------------------------------------------------------------
 * radio_init()
 *
 * Purpose:
 *   Open the RF driver, configure the PHY, set frequency, set TX power,
 *   and leave RF switch in safe RX state.
 *
 * Returns: true on success, false if RF driver fails to open.
 * Call once from rfTask() before any TX or RX.
 * --------------------------------------------------------------------- */
bool radio_init(void)
{
    RF_Params rfParams;
    RF_Params_init(&rfParams);

    /* Open RF driver with 2-GFSK 250kbps PHY.
     * SCK_RF_MODE   = RF_prop_2gfsk250kbps_0
     * SCK_CMD_SETUP = RF_cmdPropRadioDivSetup_2gfsk250kbps_0 */
    sRfHandle = RF_open(&sRfObject,
                        &SCK_RF_MODE,
                        (RF_RadioSetup *)&SCK_CMD_SETUP,
                        &rfParams);

    if (sRfHandle == NULL)
    {
        return false;
    }

    /* Set TX power per compile-time build target.
     * SCK-DEV: TX_POWER -- BENCH=0dBm, FIELD=+20dBm */
#if defined(TX_POWER) && (TX_POWER == FIELD)
    radio_setTxPower(SCK_TX_POWER_FIELD_DBM);
#else
    radio_setTxPower(SCK_TX_POWER_BENCH_DBM);
#endif

    /* Set frequency -- run synchronously so CMD_FS completes before
     * CMD_PROP_RX is posted in radio_rxStart() below.
     * Using RF_postCmd here leaves CMD_FS pending in the queue when
     * radio_rxStart() tries to post CMD_PROP_RX, which can block. */
    RF_runCmd(sRfHandle, (RF_Op *)&SCK_CMD_FS, RF_PriorityNormal, NULL, 0);

    /* RF switch to safe RX state -- PA off, 2.4GHz path selected */
    radio_rfSwitchSet(false);

    sRadioReady = true;

    /* Start RX immediately after init. */
    bool rxOk = radio_rxStart();

    /* Boot diagnostic: 3 rapid flashes = RX started successfully.
     * Remove after RF RX is confirmed working end-to-end. */
    for (int i = 0; i < 3; i++)
    {
        GPIO_write(CONFIG_GPIO_GLED, 1); usleep(80000);
        GPIO_write(CONFIG_GPIO_GLED, 0); usleep(80000);
    }

    return rxOk;
}

/* -----------------------------------------------------------------------
 * radio_transmit()
 *
 * Purpose:
 *   Transmit a single packet. Prepends length byte (bVarLen=1 mode),
 *   switches RF path to TX, runs CMD_PROP_TX, switches back to RX.
 *   Cancels any active RX command before transmitting.
 *
 * Parameters:
 *   buf -- pointer to packet data (CCSDS-framed)
 *   len -- packet length in bytes (not including length byte)
 *
 * Returns: true if TX completed successfully, false on error.
 *
 * SCK-DEV: TIMING -- Blocks until TX completes (~4ms for 128 bytes).
 *   Do not call from ISR context. RF task only.
 * --------------------------------------------------------------------- */
bool radio_transmit(const uint8_t *buf, uint16_t len)
{
    if (!sRadioReady || buf == NULL || len == 0 || len > 255)
    {
        return false;
    }

    /* If RX is running, cancel it explicitly before TX.
     * RF_runCmd cancels active commands but may block waiting for
     * acknowledgement. RF_cancelCmd with abort=1 forces immediate
     * cancellation without waiting. */
    if (sRxRunning)
    {
        RF_cancelCmd(sRfHandle, RF_CMDHANDLE_FLUSH_ALL, 1);
        sRxRunning = false;
    }

    /* bVarLen=1: RF core expects first byte to be packet length */
    sTxBuf[0] = (uint8_t)len;
    memcpy(sTxBuf + 1, buf, len);

    /* Switch RF path to TX -- enable PA before keying up */
    radio_rfSwitchSet(true);

    SCK_CMD_TX.pktLen = len + 1;
    SCK_CMD_TX.pPkt   = sTxBuf;
    SCK_CMD_TX.startTrigger.triggerType = TRIG_NOW;

    /* RF_runCmd cancels any active RX command, then blocks until TX done.
     * SCK-DEV: TIMING -- At 250kbps, 128 bytes = ~4ms on-air */
    RF_EventMask result = RF_runCmd(sRfHandle,
                                    (RF_Op *)&SCK_CMD_TX,
                                    RF_PriorityNormal,
                                    NULL,
                                    0);

    /* TX cancelled active RX -- mark as not running */
    sRxRunning = false;

    if (result & RF_EventLastCmdDone)
    {
        telemetry_update_tx();
    }

    /* Switch back to RX path */
    radio_rfSwitchSet(false);
    RF_yield(sRfHandle);

    /* Small delay after RF_yield to allow RF core to power down completely
     * before radio_rxStart() posts CMD_PROP_RX. Without this delay,
     * RF_postCmd in radio_rxStart() can block waiting for the RF core
     * to acknowledge the new command while it is still powering down.
     * 10ms is sufficient -- RF core power-down takes ~1ms typically. */
    usleep(10000);

    /* Restart RX after TX -- board must be listening between commands */
    if (!radio_rxStart())
    {
        /* RX restart failed -- 4 rapid flashes indicates RF error */
        for (int i = 0; i < 4; i++)
        {
            GPIO_write(CONFIG_GPIO_GLED, 1); usleep(80000);
            GPIO_write(CONFIG_GPIO_GLED, 0); usleep(80000);
        }
    }

    /* Brief delay to let RF core fully acknowledge the RX command.
     * Without this, a subsequent RF_cancelCmd may not cancel cleanly
     * if called before the RF core has processed the CMD_PROP_RX. */
    usleep(5000);  /* 5ms -- RF core command processing latency */

    return (result & RF_EventLastCmdDone) ? true : false;
}

/* -----------------------------------------------------------------------
 * radio_rxStart()  [module-private]
 *
 * Purpose:
 *   Initialize the RX data queue and post CMD_PROP_RX with callback.
 *   Called automatically from radio_receive() on first use and after TX.
 * --------------------------------------------------------------------- */
static bool radio_rxStart(void)
{
    static bool sQueueInitialized = false;

    if (!sQueueInitialized)
    {
        if (RFQueue_defineQueue(&sRxQueue,
                                sRxDataEntryBuffer,
                                sizeof(sRxDataEntryBuffer),
                                SCK_RX_NUM_ENTRIES,
                                SCK_RX_BUF_SIZE + SCK_RX_NUM_APPENDED))
        {
            return false;
        }

        SCK_CMD_RX.pQueue                   = &sRxQueue;
        SCK_CMD_RX.pOutput                  = NULL;
        SCK_CMD_RX.rxConf.bAutoFlushIgnored = 1;
        SCK_CMD_RX.rxConf.bAutoFlushCrcErr  = 1;
        SCK_CMD_RX.rxConf.bIncludeHdr       = 0;
        SCK_CMD_RX.rxConf.bAppendStatus     = 1;
        SCK_CMD_RX.rxConf.bAppendRssi       = 1;
        SCK_CMD_RX.maxPktLen                = SCK_RX_BUF_SIZE;
        SCK_CMD_RX.pktConf.bRepeatOk        = 1;
        SCK_CMD_RX.pktConf.bRepeatNok       = 1;

        sQueueInitialized = true;
    }

    SCK_CMD_RX.status                   = IDLE;
    SCK_CMD_RX.startTrigger.triggerType = TRIG_NOW;
    SCK_CMD_RX.endTrigger.triggerType   = TRIG_NEVER;

    radio_rfSwitchSet(false);

    RF_postCmd(sRfHandle,
               (RF_Op *)&SCK_CMD_RX,
               RF_PriorityNormal,
               radio_rxCallback,
               RF_EventRxEntryDone);

    sRxRunning = true;
    return true;
}

/* -----------------------------------------------------------------------
 * radio_rxReady()
 *
 * Purpose:
 *   Non-blocking poll. Returns true if a packet is waiting in the
 *   staging buffer. Call from RF task loop before radio_receive().
 * --------------------------------------------------------------------- */
bool radio_rxReady(void)
{
    return sRxPacketReady;
}

bool radio_isRxRunning(void)
{
    return sRxRunning;
}

/* -----------------------------------------------------------------------
 * radio_receive()
 *
 * Purpose:
 *   Copy one received packet from the staging buffer into caller's buf.
 *   Starts the background RX command on first call and after every TX.
 *   Non-blocking -- returns false immediately if no packet ready.
 *
 * Parameters:
 *   buf    -- caller buffer to copy packet into
 *   maxLen -- size of buf
 *   rxLen  -- actual packet bytes written (output)
 *
 * Returns: true if packet copied, false if no packet ready or error.
 *
 * SCK-DEV: TIMING -- Non-blocking after first call. Poll
 *   radio_rxReady() first to avoid copy overhead when no packet waiting.
 * --------------------------------------------------------------------- */
bool radio_receive(uint8_t *buf, uint16_t maxLen, uint16_t *rxLen)
{
    if (!sRadioReady || buf == NULL || rxLen == NULL)
    {
        return false;
    }

    /* (Re)start RX if not running -- first call or after TX */
    if (!sRxRunning)
    {
        if (!radio_rxStart())
        {
            return false;
        }
    }

    /* Non-blocking check */
    if (!sRxPacketReady)
    {
        *rxLen = 0;
        return false;
    }

    /* Packet ready -- flash LED to confirm */
    GPIO_write(CONFIG_GPIO_GLED, 1); usleep(100000);
    GPIO_write(CONFIG_GPIO_GLED, 0);

    /* Copy from staging buffer -- sRxStageLen set by callback */
    uint8_t copyLen = sRxStageLen;
    if (copyLen > maxLen)
    {
        copyLen = (uint8_t)maxLen;
    }

    memcpy(buf, sRxStageBuf, copyLen);
    *rxLen = copyLen;

    /* Clear ready flag so callback can stage the next packet */
    sRxPacketReady = false;

    return true;
}

/* -----------------------------------------------------------------------
 * radio_setTxPower()
 *
 * Purpose:
 *   Set RF TX power using the appropriate PA table.
 *   SDK 8_32 has two separate tables -- STD (0-5dBm) and HP (20dBm).
 *
 * Parameters:
 *   dbm -- desired power in dBm (0 for bench, 20 for field)
 *
 * SCK-DEV: TX_POWER -- bench uses STD table, field uses HP table.
 * --------------------------------------------------------------------- */
void radio_setTxPower(int8_t dbm)
{
    if (sRfHandle == NULL)
    {
        return;
    }

    RF_TxPowerTable_Entry *table;
    if (dbm > 5)
    {
        table = SCK_TX_PWR_TABLE_HP;   /* txPowerTable_2400_pa20 -- field */
    }
    else
    {
        table = SCK_TX_PWR_TABLE_STD;  /* txPowerTable_2400_pa5  -- bench */
    }

    RF_TxPowerTable_Value val = RF_TxPowerTable_findValue(table, dbm);

    if (val.rawValue != RF_TxPowerTable_INVALID_VALUE)
    {
        RF_setTxPower(sRfHandle, val);
    }
}

/* -----------------------------------------------------------------------
 * radio_rfSwitchSet()
 *
 * Purpose:
 *   Drive SKY13317-373LF RF switch GPIOs for TX or RX path.
 *
 * Parameters:
 *   txMode -- true = TX (PA enabled), false = RX (PA disabled)
 *
 * SKY13317 control:
 *   DIO28 (RF_SW_2G4): high = 2.4GHz path selected
 *   DIO29 (RF_SW_PA):  high = PA enabled (TX), low = PA off (RX)
 *
 * SCK-DEV: RF_CONFIG -- Update DIO assignments here and in
 *   sck2400.syscfg if RF switch wiring changes on SCK-2400 PCB.
 * --------------------------------------------------------------------- */
void radio_rfSwitchSet(bool txMode)
{
    if (txMode)
    {
        GPIO_write(RF_SW_2G4, 1);   /* select 2.4GHz path */
        GPIO_write(RF_SW_PA,  1);   /* enable PA          */
    }
    else
    {
        GPIO_write(RF_SW_2G4, 1);   /* keep 2.4GHz path   */
        GPIO_write(RF_SW_PA,  0);   /* disable PA for RX  */
    }
}